# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://carneybill.github.io/"
languageCode = "en-AU"
title = "Bill Carney"

# Metadata
[params]
  author = "Bill Carney"
  description = "Billstuff for the website"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "/images/lightbulb.jpg"
  title = "Not just another marketing guy"
  description = "The best marketing is iterative with the right mix of innovative strategic thinking, creative campaign design, and data-driven decision-making."

# Navigation section
[params.nav]
  mission = "Tools"
  services = "About"
  team = "About"
  contact = "Contact"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/nice-things.jpeg"
    [[params.mission.images.list]]
      img = "images/pexels-photo-106344.jpeg"
    [[params.mission.images.list]]
      img = "images/fashion-men-vintage-colorful.jpg"
    [[params.mission.images.list]]
      img = "images/pexels-photo-266176.jpeg"

  [[params.mission.item]]
    weight = 1
    name = "marketing"
    title = "Marketing"
    subtitle = "It's about a deliberate approach."
    description = "<p>Marketing should help you create, measure and optimize the journeys of your prospects and customers.  Your goal is to deliver specific content that compels them to engage, self-nurture, and move faster through the learning and buying cycle. Every user isn't automatically qualified, you need to discover the right people and earn trust, ultimately building a community of advocates.</p><ul class='checked'><li>Everything is a 'Test and Learn'</li><li>Leverage content created by credible sources</li><li>Create workflows that are compelling</li><li>Your prospect has more knowledge than you do</li><p><br><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 2
    name = "technology"
    title = "Technology"
    subtitle = "Anyone that calls themselves a 'guru' usually isn't."
    description = "<p>The constant change in Martech means you have to be open to the many emerging technologies that can help you do your job.  The end goal doesn't change, deliver compelling content and create remarkable experiences. Without an overall view and cohesive strategy, any single component failure can destroy all your efforts. </p><ul class='checked'><li>Marketing Automation Platforms</li><li>Customer Relationship Management Platforms</li><li>Content Management Platforms</li><li>Web Analytics Platforms</li><li>A/B Testing Platforms</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 3
    name = "Analysis"
    title = "Analysis"
    subtitle = "The facts are friendly."
    description = "<p>The goal of analytics is to help you determine if your objective has been met - duh. It's a bit more difficult determining program or campaign numbers that you can track to your objectives. Assigning attribution to an interaction has never been more complicated. The sheer number of marketing channels and devices has added levels of complexity. There are plenty of organizations out there that don’t have much of an understanding of their attribution metrics. Lack of understanding does not give you permission to not keep investigating and developing theories. </p><ul class='checked'><li>First touch attribution</li><li>Last touch attribution</li><li>Multi touch attribution</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"


# Services section
[params.services]
  enable = true
  video = false
  vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Who is Bill?"
  description = "I’m just a marketing guy with experience in delivering innovative programs and campaigns that accelerate profitable growth, increase brand value, and expand market share. I use years of experience with various marketing technologies, content leverage techniques, and analytics to help companies grow quickly and achieve meaningful differentiation."

  [[params.services.item]]
    icon = "icon-present"
    title = "Demand Generation"
    description = "Demand generation has a core goal to build and nurture prospect and customer relationships for the long term. To do this effectively, marketers need to do things like responding to customer questions on Twitter, promote blog posts through social channels, host webinars, and run email marketing campaigns. It's not a quick fix, a banner ad, an email blast, or a call center blitz."

  [[params.services.item]]
    icon = "icon-eye"
    title = "Community"
    description = "The top three business objectives for communities are customer retention (70%), customer engagement (64%), and revenue (34%).* That's why companies with a good product have nurtured customers as brand advocates with online communities, where they create peer influence in target markets.  *Forrester’s The State of Loyalty Programs Study"

  [[params.services.item]]
    icon = "icon-paper-plane"
    title = "Conversations"
    description = "Talking to your customers isn’t about blindly spitting out messages to everyone, or counting every customer contact as ‘qualified’ for a conversation. All contacts are NOT equal. If you design a system poorly you’ll have so many unproductive conversations your high value qualified contacts will suffer for it and subsequently, your company will suffer as well. "

  [[params.services.item]]
    icon = "icon-rocket"
    title = "Speed"
    description = "I believe that speed in marketing is a mindset. Paraphrasing Gary Vanderchuck - 'Speed beats everything else'.  Speed is so important to me, my old twitter handle (recommended by a friend) used to be biasforaction. Speed for speed's sake isn't the goal, but doing something and then learning something is much better than inaction. Efforts once completed must be measured. You then continuously and incrementally improve the results over time - but you are constantly moving."

  [[params.services.item]]
    icon = "icon-flask"
    title = "Test and Learn"
    description = "Along with speed I believe that test and learn is a mindset in marketing as well. A test and learn approach gives you permission to experiment and build upon successes while learning from failures. With technology improvements, it's getting easier to take on large slow moving organizations that refuse to try innovative approaches. You have to be ready to embrace failures and be open-minded enough to take criticism."

  [[params.services.item]]
    icon = "icon-people"
    title = "Account Based"
    description = "Marketing is responsible for the customer lifecycle and we must deliver a specific experience at every touch. The old 'see what sticks' approach doesn't work anymore. Clients, though not unique, like to feel that way and focus on accounts takes more thought and effort. Account-level specificity has been made easier through advances in tech and allows this focus with greater scaling capability."

# Work section
[params.work]
  enable = false

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_1.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_4.jpg"

# Team section
[params.team]
  enable = false
  title = ""
  description = ""

  [[params.team.item]]
    name = "Bill Carney"
    position = "Marketing Guy"
    description = ""
    img = "images/headshot.jpg"
    facebook = "https://www.facebook.com/carney.bill"
    twitter = "https://twitter.com/_billc"
    instagram = "https://www.instagram.com/_billc/"
    github = "https://github.com/carneybill"
    linkedin = "https://www.linkedin.com/in/bcarney/"

  [[params.team.item]]

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"

# Contact section
[params.contact]
  enable = true
  title = "Contact"
  message = "If you have any questions or would love to just connect, please don’t hesitate to contact me."

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. <br> Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Demo Images: <a href='http://pexels.com/' target='_blank'>Pexels</a><br>Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small></p>"
  facebook = "https://www.facebook.com/carney.bill"
  twitter = "https://twitter.com/_billc"
  instagram = "https://www.instagram.com/_billc/"
  github = "https://github.com/carneybill"
  linkedin = "https://www.linkedin.com/in/bcarney/"

  
